Jdp230101 12
piotr-grosicki/project-jdp-2301-01 pull request #13
Opened 2023-01-09 10:45 UTC by CodeStudent1742

Initial Entity implementation of Product. Need to add Relations on later stage

2023-01-09 14:21 UTC, piotr-grosicki requested changes
tak jak pisalem na komunikatorze o relacjach + konflikty w pliku build.gradle (probujesz kolejny raz dodac lomboka

2023-01-10 08:43 UTC, CodeStudent1742 commented
Product with relations. Cart and Order needed part added

2023-01-10 18:44 UTC, waleczna requested changes

2023-01-10 18:44 UTC, waleczna commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +@Entity(name = "CARTS")
`CARTS` should be a table name but not an entity name. It should look like: 
```
@Entity
@Table (name = "CARTS")
```

2023-01-10 18:44 UTC, waleczna commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +@Entity(name = "PRODUCTS")
`PRODUCTS` should be a table name but not an entity name. It should look like: 
```
@Entity
@Table (name = "PRODUCTS")
```

2023-01-10 18:44 UTC, waleczna commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +}
Missing many to many relation to `Product` entity.

2023-01-10 18:44 UTC, waleczna commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +}
Missing many to many relation to `Product` entity.

2023-01-11 09:37 UTC, CodeStudent1742 commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +@Entity(name = "PRODUCTS")
Done

2023-01-11 09:37 UTC, CodeStudent1742 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +@Entity(name = "CARTS")
Done

2023-01-11 11:35 UTC, CodeStudent1742 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +}
done

2023-01-14 19:09 UTC, BigKowalsky approved these changes
In my opinion everything is ok. I analyzed changes since the last commit, In my IntelliJ gradle is building, app also starting without problems.

2023-01-16 13:35 UTC, pietryczko approved these changes
For me, everything is ok

2023-01-16 13:41 UTC, merged