JDP230101-14
piotr-grosicki/project-jdp-2301-01 pull request #18
Opened 2023-01-10 12:45 UTC by CodeStudent1742

2023-01-10 19:20 UTC, BigKowalsky requested changes
Moim zdaniem jest OK, approve.

2023-01-10 19:21 UTC, BigKowalsky approved these changes
Pomyłka, klikam Approve.

2023-01-11 10:41 UTC, pietryczko approved these changes

2023-01-11 10:42 UTC, pietryczko commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private long userId;
Jak dla mnie ok :)

2023-01-11 11:32 UTC, merged