Jdp230101 5
piotr-grosicki/project-jdp-2301-01 pull request #4
Opened 2023-01-05 11:51 UTC by pietryczko

2023-01-05 19:57 UTC, piotr-grosicki submitted a review, later dismissed

2023-01-05 19:57 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/dto/UserDto.java
> +    private Cart cart;
dto nie moze zawierac encji, tylko inne dto a najlepiej ich id

2023-01-10 11:25 UTC, CodeStudent1742 requested changes
UserDto pole Cart cart wymaga zmiany. Analogiczne komentarze jak w pull request #5.

2023-01-11 10:44 UTC, CodeStudent1742 approved these changes
Do rozwiązania konflikt z Product przy mergownaiu

2023-01-11 11:24 UTC, pietryczko commented
> Do rozwiązania konflikt z Product przy mergownaiu

Juz rozwiązane :)

2023-01-11 18:31 UTC, BigKowalsky commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    @DeleteMapping
Moim zdaniem przy @ DeleteMapping powinna być wartość value, żeby można było wywołać to w Postmanie.

2023-01-11 18:34 UTC, BigKowalsky requested changes
Dałem jedną uwagę do adnotacji @ DeleteMapping , gdyż moim zdaniem w takiej formie nie pyknie na testach - do przedyskutowania. Poza tym wydaje się OK

2023-01-11 23:37 UTC, BigKowalsky approved these changes
Ok, teraz wydaje mi się, ze będzie w porządku.

2023-01-11 23:38 UTC, merged