Jdp230101 4
piotr-grosicki/project-jdp-2301-01 pull request #5
Opened 2023-01-05 11:52 UTC by pietryczko

2023-01-05 20:00 UTC, piotr-grosicki requested changes

2023-01-05 20:00 UTC, piotr-grosicki commented on build.gradle
> +    implementation 'org.projectlombok:lombok:1.18.22'
raz wystarczy dodac

2023-01-05 20:00 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
>  public class UserController {
dwa controllery zrobione na jednej branchy?

2023-01-05 20:00 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/dto/OrderDto.java
> +    private Cart cart;
dto nie moze zawierac encji, powinno zawierac inne dto lub ich id

2023-01-10 11:21 UTC, CodeStudent1742 reviewed
Są pewne rozbieżności w build.gradle. OrderStatus był już połączony z main.  Wydaje się, że da się te rozbieżności rozwiązać mergując z rozwiązywaniem konfliktow. Upewnie się czy takie podejście jest ok i jeśli tak to zaakceptuje

2023-01-11 10:35 UTC, CodeStudent1742 approved these changes
Zbędne klasy domenowe ale nie przeszkadzają. Przy mergowaniu będzie trzeba rozwiązać konflikt z Product( bo już aktualniejszy w main)

2023-01-11 18:42 UTC, BigKowalsky approved these changes
Kod moim zdaniem jest ok. Pewnie przy merge pojawią się konflikty do rozwiązania z uwagi na akcepty kilku branchy. Najpierw "zmerdżuj" te branche bez konfliktów.

2023-01-11 21:10 UTC, merged